In [1]:
import numpy as np

In [4]:
# 1. Create an array of all even integers from 30 to 70
even_integers = np.arange(30, 71, 2)
print("Even integers from 30 to 70:\n", even_integers)

Even integers from 30 to 70:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [5]:
# 2. Generate an array of 15 random numbers from a standard normal distribution
random_normal = np.random.randn(15)
print("\n15 random numbers from a standard normal distribution:\n", random_normal)



15 random numbers from a standard normal distribution:
 [ 1.27113841 -2.02769505 -0.59488865  1.25964142 -0.57273112  0.66632531
 -0.24122577  0.4670089  -0.70597357  0.39456966 -0.83156389 -0.20715808
 -2.16505205 -0.11854482  0.14282936]


In [6]:
# 3. Compute the cross-product of two matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
cross_product = np.cross(A, B)
print("\nCross-product of two matrices:\n", cross_product)


Cross-product of two matrices:
 [[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


In [7]:
# 4. Compute the determinant of an array
determinant = np.linalg.det(A)
print("\nDeterminant of the array:\n", determinant)


Determinant of the array:
 6.66133814775094e-16


In [8]:
# 5. Create a 3x3x3 array with random values
random_3x3x3 = np.random.random((3, 3, 3))
print("\n3x3x3 array with random values:\n", random_3x3x3)


3x3x3 array with random values:
 [[[0.31357012 0.3392987  0.29186629]
  [0.64975695 0.40594046 0.45351945]
  [0.56407708 0.35647967 0.81816123]]

 [[0.61028185 0.4515591  0.32371233]
  [0.02152192 0.20036898 0.29918885]
  [0.90545189 0.60749202 0.13756426]]

 [[0.28631791 0.32660209 0.43781035]
  [0.37278789 0.01244357 0.78458628]
  [0.72461079 0.0714274  0.3072434 ]]]


In [9]:
# 6. Create a 5x5 array with random values and find the minimum and maximum values
random_5x5 = np.random.random((5, 5))
min_value = random_5x5.min()
max_value = random_5x5.max()
print("\n5x5 array with random values:\n", random_5x5)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


5x5 array with random values:
 [[0.07752027 0.35017412 0.46772229 0.32651022 0.95468431]
 [0.98186729 0.77936469 0.69695148 0.24508492 0.07151471]
 [0.97105288 0.1757296  0.15748796 0.44525476 0.64447315]
 [0.38542373 0.19242293 0.475932   0.32169366 0.01520368]
 [0.02925269 0.3091196  0.51407351 0.41421446 0.8710864 ]]
Minimum value: 0.015203684793382743
Maximum value: 0.9818672868857878


In [10]:
# 7. Compute the mean, standard deviation, and variance along the second axis
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean_axis_2 = np.mean(C, axis=1)
std_dev_axis_2 = np.std(C, axis=1)
variance_axis_2 = np.var(C, axis=1)
print("\nMean along the second axis:\n", mean_axis_2)
print("Standard deviation along the second axis:\n", std_dev_axis_2)
print("Variance along the second axis:\n", variance_axis_2)


Mean along the second axis:
 [2. 5. 8.]
Standard deviation along the second axis:
 [0.81649658 0.81649658 0.81649658]
Variance along the second axis:
 [0.66666667 0.66666667 0.66666667]
